apiVersion: v1
kind: Secret
metadata:
  name: kubectl-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
  minio-access: bWluaW9hY2Nlc3NrZXk=
  minio-secret: bWluaW9zZWNyZXRrZXk=
  mysql-user: cm9vdA==
  mysql-password: bW9uZ29wYXNzd29yZA==
